exports.SASS = { name: "Sass", href: "sass-lang.com" };
exports.NODEJS = { name: "Node.js", href: "nodejs.org/en/" };
exports.EXPRESSJS = { name: "Express", href: "expressjs.com/" };
exports.KOAJS = { name: "Koa", href: "koajs.com" };
exports.REACTJS = { name: "React", href: "reactjs.org" };
exports.REDUX = { name: "Redux", href: "redux.js.org" };
exports.BOOTSTRAP = { name: "Bootstrap", href: "getbootstrap.com" };
exports.MATERIALIZE = { name: "Materialize", href: "materializecss.com" };
exports.MONGODB = { name: "MongoDB", href: "www.mongodb.com" };
exports.STRIPE = { name: "Stripe", href: "stripe.com" };
exports.D3JS = { name: "D3.js", href: "d3js.org" };
exports.JQUERY = { name: "jQuery", href: "jquery.com" };
exports.PASSPORT = { name: "Passport", href: "bit.ly/2NTNJiw" };
exports.CHARTJS = { name: "Chart.js", href: "www.chartjs.org"}
